### ISSUE TITLE
Detecting the sentences

### ISSUE THREAD

**Issue by nazmicancalik** [derlem/susamuru#8]
We realized that breaking the wikipedia text into sentences is tricky. We have checked [nltk](https://www.nltk.org/), however we are not quite sure how to do it.

Can you give us more insights? @onurgu

**Comment by onurgu** [comment]
1) Can you give more details?

2) Yes, there will be complications. However, at this stage, I suggest
   i) clean the Mediawiki Markup from source using a parser (does your tool support it?)
   ii) then use nltk to split that.
and accept the output and show us to assess the quality.

**Comment by nazmicancalik** [comment]
We are extracting the sentences with nltk. It seems to be pretty accurate. That's why I am closing this issue for now.
